mv ./logdog/story.check ./logdog/task.check
mv ./logdog/story.pm ./logdog/task.pm
mv ./package-generic/modules/yum/story.check ./package-generic/modules/yum/task.check
mv ./package-generic/modules/yum/story.bash ./package-generic/modules/yum/task.bash
mv ./package-generic/modules/autoremove/story.check ./package-generic/modules/autoremove/task.check
mv ./package-generic/modules/autoremove/story.bash ./package-generic/modules/autoremove/task.bash
mv ./package-generic/modules/pacman/story.check ./package-generic/modules/pacman/task.check
mv ./package-generic/modules/pacman/story.bash ./package-generic/modules/pacman/task.bash
mv ./package-generic/modules/opkg/story.bash ./package-generic/modules/opkg/task.bash
mv ./package-generic/modules/apk-update/story.check ./package-generic/modules/apk-update/task.check
mv ./package-generic/modules/apk-update/story.bash ./package-generic/modules/apk-update/task.bash
mv ./package-generic/modules/apk/story.bash ./package-generic/modules/apk/task.bash
mv ./package-generic/modules/apt-get/story.check ./package-generic/modules/apt-get/task.check
mv ./package-generic/modules/apt-get/story.bash ./package-generic/modules/apt-get/task.bash
mv ./ruby-test/story.rb ./ruby-test/task.rb
mv ./ruby-test/story.check ./ruby-test/task.check
mv ./azure-cert-show/story.bash ./azure-cert-show/task.bash
mv ./git-commit/modules/commit/story.bash ./git-commit/modules/commit/task.bash
mv ./git-commit/modules/check-spell/story.bash ./git-commit/modules/check-spell/task.bash
mv ./jira-rest-class-smoke/story.check ./jira-rest-class-smoke/task.check
mv ./jira-rest-class-smoke/story.bash ./jira-rest-class-smoke/task.bash
mv ./csvtotable/story.bash ./csvtotable/task.bash
mv ./longman-online/modules/download/story.check ./longman-online/modules/download/task.check
mv ./longman-online/modules/download/story.bash ./longman-online/modules/download/task.bash
mv ./longman-online/modules/process-file/story.pl ./longman-online/modules/process-file/task.pl
mv ./ssh-sudo-try/modules/ssh-and-sudo/story.bash ./ssh-sudo-try/modules/ssh-and-sudo/task.bash
mv ./perl-app/story.check ./perl-app/task.check
mv ./perl-app/story.bash ./perl-app/task.bash
mv ./df-check/story.check ./df-check/task.check
mv ./df-check/story.bash ./df-check/task.bash
mv ./weather/story.bash ./weather/task.bash
mv ./nagios-split-host/story.bash ./nagios-split-host/task.bash
mv ./p6-algorithm-minmaxheap-smoke/modules/sort-array/story.check ./p6-algorithm-minmaxheap-smoke/modules/sort-array/task.check
mv ./p6-algorithm-minmaxheap-smoke/modules/sort-array/story.bash ./p6-algorithm-minmaxheap-smoke/modules/sort-array/task.bash
mv ./memcached-check/story.check ./memcached-check/task.check
mv ./memcached-check/story.bash ./memcached-check/task.bash
mv ./azure-arm-deploy/story.bash ./azure-arm-deploy/task.bash
mv ./nginx-check-example/story.check ./nginx-check-example/task.check
mv ./nginx-check-example/story.bash ./nginx-check-example/task.bash
mv ./azure-web-app-appsettings/story.check ./azure-web-app-appsettings/task.check
mv ./azure-web-app-appsettings/story.bash ./azure-web-app-appsettings/task.bash
mv ./sparky-no-index-update/story.bash ./sparky-no-index-update/task.bash
mv ./templater/story.check ./templater/task.check
mv ./templater/modules/generate-content/story.check ./templater/modules/generate-content/task.check
mv ./templater/modules/generate-content/story.pl ./templater/modules/generate-content/task.pl
mv ./templater/story.bash ./templater/task.bash
mv ./ssh-test1/story.check ./ssh-test1/task.check
mv ./ssh-test1/story.bash ./ssh-test1/task.bash
mv ./azure-token/modules/parse-token/story.pl ./azure-token/modules/parse-token/task.pl
mv ./azure-token/modules/get-token/story.bash ./azure-token/modules/get-token/task.bash
mv ./nginx-check/modules/etime/story.check ./nginx-check/modules/etime/task.check
mv ./nginx-check/modules/etime/story.bash ./nginx-check/modules/etime/task.bash
mv ./nginx-check/modules/etime/story.pm ./nginx-check/modules/etime/task.pm
mv ./nginx-check/modules/ps-aux/story.check ./nginx-check/modules/ps-aux/task.check
mv ./nginx-check/modules/ps-aux/story.bash ./nginx-check/modules/ps-aux/task.bash
mv ./module-release/story.check ./module-release/task.check
mv ./module-release/story.bash ./module-release/task.bash
mv ./zef/story.bash ./zef/task.bash
mv ./short/story.bash ./short/task.bash
mv ./mi6-dist-ini/story.bash ./mi6-dist-ini/task.bash
mv ./svn-to-git-submodules/story.check ./svn-to-git-submodules/task.check
mv ./svn-to-git-submodules/modules/submodule-add/story.check ./svn-to-git-submodules/modules/submodule-add/task.check
mv ./svn-to-git-submodules/modules/submodule-add/story.bash ./svn-to-git-submodules/modules/submodule-add/task.bash
mv ./svn-to-git-submodules/modules/git-pull/story.check ./svn-to-git-submodules/modules/git-pull/task.check
mv ./svn-to-git-submodules/modules/git-pull/story.bash ./svn-to-git-submodules/modules/git-pull/task.bash
mv ./svn-to-git-submodules/modules/clear-cache/story.check ./svn-to-git-submodules/modules/clear-cache/task.check
mv ./svn-to-git-submodules/modules/clear-cache/story.bash ./svn-to-git-submodules/modules/clear-cache/task.bash
mv ./svn-to-git-submodules/story.pm ./svn-to-git-submodules/task.pm
mv ./azure-adls-fs-remove/modules/read-folder/story.bash ./azure-adls-fs-remove/modules/read-folder/task.bash
mv ./azure-adls-fs-remove/modules/remove-fs/story.bash ./azure-adls-fs-remove/modules/remove-fs/task.bash
mv ./sshd-check/story.check ./sshd-check/task.check
mv ./sshd-check/story.bash ./sshd-check/task.bash
mv ./puck/story.bash ./puck/task.bash
mv ./net-ping/story.check ./net-ping/task.check
mv ./net-ping/story.pl ./net-ping/task.pl
mv ./png-compress/story.pl ./png-compress/task.pl
mv ./csv-add-column/story.bash ./csv-add-column/task.bash
mv ./file-compare-columns/story.pl ./file-compare-columns/task.pl
mv ./file/story.check ./file/task.check
mv ./file/story.bash ./file/task.bash
mv ./timetest/story.check ./timetest/task.check
mv ./timetest/story.bash ./timetest/task.bash
mv ./perl-file-dir-dumper-smoke/modules/simple-dir-dump/story.check ./perl-file-dir-dumper-smoke/modules/simple-dir-dump/task.check
mv ./perl-file-dir-dumper-smoke/modules/simple-dir-dump/story.bash ./perl-file-dir-dumper-smoke/modules/simple-dir-dump/task.bash
mv ./cpan-upload/story.bash ./cpan-upload/task.bash
mv ./sparky-index-update/story.bash ./sparky-index-update/task.bash
mv ./diff-so-fancy-test/story.check ./diff-so-fancy-test/task.check
mv ./diff-so-fancy-test/story.bash ./diff-so-fancy-test/task.bash
mv ./bash-snippets-interactive-test/modules/currency/example1/story.check ./bash-snippets-interactive-test/modules/currency/example1/task.check
mv ./bash-snippets-interactive-test/modules/currency/example1/story.pl ./bash-snippets-interactive-test/modules/currency/example1/task.pl
mv ./bash-snippets-interactive-test/modules/currency/example2/story.check ./bash-snippets-interactive-test/modules/currency/example2/task.check
mv ./bash-snippets-interactive-test/modules/currency/example2/story.pl ./bash-snippets-interactive-test/modules/currency/example2/task.pl
mv ./goss/modules/validate/story.check ./goss/modules/validate/task.check
mv ./goss/modules/validate/story.bash ./goss/modules/validate/task.bash
mv ./goss/modules/generate-goss-yaml/story.check ./goss/modules/generate-goss-yaml/task.check
mv ./goss/modules/generate-goss-yaml/story.pl ./goss/modules/generate-goss-yaml/task.pl
mv ./goss/modules/install/story.check ./goss/modules/install/task.check
mv ./goss/modules/install/story.bash ./goss/modules/install/task.bash
mv ./awk-select-lines/story.bash ./awk-select-lines/task.bash
mv ./perlbrew/story.check ./perlbrew/task.check
mv ./perlbrew/story.bash ./perlbrew/task.bash
mv ./postgresql-check/story.check ./postgresql-check/task.check
mv ./postgresql-check/story.bash ./postgresql-check/task.bash
mv ./minion-check/story.check ./minion-check/task.check
mv ./minion-check/modules/check-worker/story.check ./minion-check/modules/check-worker/task.check
mv ./minion-check/modules/check-worker/story.bash ./minion-check/modules/check-worker/task.bash
mv ./minion-check/modules/last-task/story.check ./minion-check/modules/last-task/task.check
mv ./minion-check/modules/last-task/story.bash ./minion-check/modules/last-task/task.bash
mv ./minion-check/story.pm ./minion-check/task.pm
mv ./cheat/story.bash ./cheat/task.bash
mv ./foo-test/story.bash ./foo-test/task.bash
mv ./azure-kv-show/modules/fetch-kv/story.bash ./azure-kv-show/modules/fetch-kv/task.bash
mv ./azure-kv-show/modules/print/story.pl ./azure-kv-show/modules/print/task.pl
mv ./azure-list-context/story.ps1 ./azure-list-context/task.ps1
mv ./service/modules/stop/story.check ./service/modules/stop/task.check
mv ./service/modules/stop/story.bash ./service/modules/stop/task.bash
mv ./service/modules/start/story.check ./service/modules/start/task.check
mv ./service/modules/start/story.bash ./service/modules/start/task.bash
mv ./service/modules/disable/story.check ./service/modules/disable/task.check
mv ./service/modules/disable/story.bash ./service/modules/disable/task.bash
mv ./service/modules/enable/story.check ./service/modules/enable/task.check
mv ./service/modules/enable/story.bash ./service/modules/enable/task.bash
mv ./file-touch-smoke/modules/change-access-time/story.check ./file-touch-smoke/modules/change-access-time/task.check
mv ./file-touch-smoke/modules/change-access-time/story.bash ./file-touch-smoke/modules/change-access-time/task.bash
mv ./file-touch-smoke/modules/create-file-if-not-exist/story.check ./file-touch-smoke/modules/create-file-if-not-exist/task.check
mv ./file-touch-smoke/modules/create-file-if-not-exist/story.bash ./file-touch-smoke/modules/create-file-if-not-exist/task.bash
mv ./python-sparrow-plugin/story.py ./python-sparrow-plugin/task.py
mv ./python-sparrow-plugin/story.check ./python-sparrow-plugin/task.check
mv ./azure-adls-acl-check/modules/check-acl/story.check ./azure-adls-acl-check/modules/check-acl/task.check
mv ./azure-adls-acl-check/modules/check-acl/story.pl ./azure-adls-acl-check/modules/check-acl/task.pl
mv ./azure-adls-acl-check/modules/get-acl/story.bash ./azure-adls-acl-check/modules/get-acl/task.bash
mv ./azure-adls-acl-check/story.bash ./azure-adls-acl-check/task.bash
mv ./mojolicious-app-smoke/modules/hello/story.check ./mojolicious-app-smoke/modules/hello/task.check
mv ./mojolicious-app-smoke/modules/hello/story.bash ./mojolicious-app-smoke/modules/hello/task.bash
mv ./mojolicious-app-smoke/modules/welcome-page/story.check ./mojolicious-app-smoke/modules/welcome-page/task.check
mv ./mojolicious-app-smoke/modules/welcome-page/story.bash ./mojolicious-app-smoke/modules/welcome-page/task.bash
mv ./mojolicious-app-smoke/modules/bye/story.check ./mojolicious-app-smoke/modules/bye/task.check
mv ./mojolicious-app-smoke/modules/bye/story.bash ./mojolicious-app-smoke/modules/bye/task.bash
mv ./mojolicious-app-smoke/modules/echo-name/story.check ./mojolicious-app-smoke/modules/echo-name/task.check
mv ./mojolicious-app-smoke/modules/echo-name/story.bash ./mojolicious-app-smoke/modules/echo-name/task.bash
mv ./azure-app-service-info/story.check ./azure-app-service-info/task.check
mv ./azure-app-service-info/story.ps1 ./azure-app-service-info/task.ps1
mv ./aws-list-tag-instances/story.bash ./aws-list-tag-instances/task.bash
mv ./http-status/story.check ./http-status/task.check
mv ./http-status/story.bash ./http-status/task.bash
mv ./directory/modules/windows/delete/story.pl ./directory/modules/windows/delete/task.pl
mv ./directory/modules/windows/create/story.pl ./directory/modules/windows/create/task.pl
mv ./directory/modules/linux/delete/story.check ./directory/modules/linux/delete/task.check
mv ./directory/modules/linux/delete/story.bash ./directory/modules/linux/delete/task.bash
mv ./directory/modules/linux/create/story.check ./directory/modules/linux/create/task.check
mv ./directory/modules/linux/create/story.bash ./directory/modules/linux/create/task.bash
mv ./azure-dls-account-list/story.bash ./azure-dls-account-list/task.bash
mv ./dir-folder-start/story.pl ./dir-folder-start/task.pl
mv ./git-pull/story.bash ./git-pull/task.bash
mv ./uwp-selfsigned-cert/story.bash ./uwp-selfsigned-cert/task.bash
mv ./sqltextify/story.bash ./sqltextify/task.bash
mv ./json-lint/modules/lint/story.bash ./json-lint/modules/lint/task.bash
mv ./outth-mysql-cookbook/mysql_user_select/story.check ./outth-mysql-cookbook/mysql_user_select/task.check
mv ./outth-mysql-cookbook/mysql_user_select/story.pm ./outth-mysql-cookbook/mysql_user_select/task.pm
mv ./outth-mysql-cookbook/simple-crud/story.check ./outth-mysql-cookbook/simple-crud/task.check
mv ./outth-mysql-cookbook/simple-crud/story.pm ./outth-mysql-cookbook/simple-crud/task.pm
mv ./git-base/story.check ./git-base/task.check
mv ./git-base/modules/install-debian/story.check ./git-base/modules/install-debian/task.check
mv ./git-base/modules/install-debian/story.bash ./git-base/modules/install-debian/task.bash
mv ./git-base/modules/install-centos/story.check ./git-base/modules/install-centos/task.check
mv ./git-base/modules/install-centos/story.bash ./git-base/modules/install-centos/task.bash
mv ./git-base/modules/install-minoca/story.bash ./git-base/modules/install-minoca/task.bash
mv ./git-base/story.bash ./git-base/task.bash
mv ./ssh-sudo-check/story.check ./ssh-sudo-check/task.check
mv ./ssh-sudo-check/modules/ssh-and-check-sudo/story.check ./ssh-sudo-check/modules/ssh-and-check-sudo/task.check
mv ./ssh-sudo-check/modules/ssh-and-check-sudo/story.pm ./ssh-sudo-check/modules/ssh-and-check-sudo/task.pm
mv ./ssh-sudo-check/story.pm ./ssh-sudo-check/task.pm
mv ./nginx-example/modules/nginx-install/story.check ./nginx-example/modules/nginx-install/task.check
mv ./nginx-example/modules/nginx-install/story.bash ./nginx-example/modules/nginx-install/task.bash
mv ./nginx-example/nginx-setup/story.check ./nginx-example/nginx-setup/task.check
mv ./nginx-example/nginx-setup/story.bash ./nginx-example/nginx-setup/task.bash
mv ./yandex-disk/modules/list-files/story.bash ./yandex-disk/modules/list-files/task.bash
mv ./yandex-disk/modules/disk-info/story.bash ./yandex-disk/modules/disk-info/task.bash
mv ./yandex-disk/modules/upload-file/story.bash ./yandex-disk/modules/upload-file/task.bash
mv ./yandex-disk/modules/create-folder/story.bash ./yandex-disk/modules/create-folder/task.bash
mv ./yandex-disk/modules/download-file/story.bash ./yandex-disk/modules/download-file/task.bash
mv ./git-async-push/story.check ./git-async-push/task.check
mv ./git-async-push/story.bash ./git-async-push/task.bash
mv ./linux-proc-maps-smoke/modules/parse_maps_single_line/story.check ./linux-proc-maps-smoke/modules/parse_maps_single_line/task.check
mv ./linux-proc-maps-smoke/modules/parse_maps_single_line/story.bash ./linux-proc-maps-smoke/modules/parse_maps_single_line/task.bash
mv ./linux-proc-maps-smoke/modules/format_maps_single_line/story.check ./linux-proc-maps-smoke/modules/format_maps_single_line/task.check
mv ./linux-proc-maps-smoke/modules/format_maps_single_line/story.bash ./linux-proc-maps-smoke/modules/format_maps_single_line/task.bash
mv ./linux-proc-maps-smoke/modules/child-pid/story.check ./linux-proc-maps-smoke/modules/child-pid/task.check
mv ./linux-proc-maps-smoke/modules/child-pid/story.bash ./linux-proc-maps-smoke/modules/child-pid/task.bash
mv ./azure-sql-server-check-fw/story.check ./azure-sql-server-check-fw/task.check
mv ./azure-sql-server-check-fw/story.bash ./azure-sql-server-check-fw/task.bash
mv ./currency/story.bash ./currency/task.bash
mv ./app-cpm-wrapper/story.bash ./app-cpm-wrapper/task.bash
mv ./azure-kv-secrets-check/story.check ./azure-kv-secrets-check/task.check
mv ./azure-kv-secrets-check/story.bash ./azure-kv-secrets-check/task.bash
mv ./gcp-data-store-bookshelf/modules/list/story.rb ./gcp-data-store-bookshelf/modules/list/task.rb
mv ./gcp-data-store-bookshelf/modules/add/story.rb ./gcp-data-store-bookshelf/modules/add/task.rb
mv ./git-svn-export/story.check ./git-svn-export/task.check
mv ./git-svn-export/modules/git-svn/story.check ./git-svn-export/modules/git-svn/task.check
mv ./git-svn-export/modules/git-svn/story.bash ./git-svn-export/modules/git-svn/task.bash
mv ./git-svn-export/modules/init/story.check ./git-svn-export/modules/init/task.check
mv ./git-svn-export/modules/init/story.bash ./git-svn-export/modules/init/task.bash
mv ./git-svn-export/story.pm ./git-svn-export/task.pm
mv ./uwp-self-signed-cert/story.bash ./uwp-self-signed-cert/task.bash
mv ./git-submodules-update/story.check ./git-submodules-update/task.check
mv ./git-submodules-update/story.bash ./git-submodules-update/task.bash
mv ./mssql-check-login/modules/check/story.pl ./mssql-check-login/modules/check/task.pl
mv ./foo-generic/story.check ./foo-generic/task.check
mv ./foo-generic/story.pl ./foo-generic/task.pl
mv ./yaml-lint/modules/lint/story.bash ./yaml-lint/modules/lint/task.bash
mv ./azure-account-set/story.bash ./azure-account-set/task.bash
mv ./bitbucket-repo/story.check ./bitbucket-repo/task.check
mv ./bitbucket-repo/story.bash ./bitbucket-repo/task.bash
mv ./git-push/story.bash ./git-push/task.bash
mv ./catmandu-smoke/modules/csv-to-json/story.check ./catmandu-smoke/modules/csv-to-json/task.check
mv ./catmandu-smoke/modules/csv-to-json/story.bash ./catmandu-smoke/modules/csv-to-json/task.bash
mv ./git-dir-pull/story.bash ./git-dir-pull/task.bash
mv ./web-service-fake-smoke/modules/nowrap/story.check ./web-service-fake-smoke/modules/nowrap/task.check
mv ./web-service-fake-smoke/modules/nowrap/story.bash ./web-service-fake-smoke/modules/nowrap/task.bash
mv ./web-service-fake-smoke/modules/ciao/story.check ./web-service-fake-smoke/modules/ciao/task.check
mv ./web-service-fake-smoke/modules/ciao/story.bash ./web-service-fake-smoke/modules/ciao/task.bash
mv ./check-ssl-cert/modules/check-cert/story.check ./check-ssl-cert/modules/check-cert/task.check
mv ./check-ssl-cert/modules/check-cert/story.bash ./check-ssl-cert/modules/check-cert/task.bash
mv ./bar-script/story.check ./bar-script/task.check
mv ./bar-script/story.pl ./bar-script/task.pl
mv ./ansible-tutorial/modules/playbook-simple/story.bash ./ansible-tutorial/modules/playbook-simple/task.bash
mv ./meta6-bin/story.check ./meta6-bin/task.check
mv ./meta6-bin/story.bash ./meta6-bin/task.bash
mv ./azure-resource-list/modules/parse-resources/story.check ./azure-resource-list/modules/parse-resources/task.check
mv ./azure-resource-list/modules/parse-resources/story.pl ./azure-resource-list/modules/parse-resources/task.pl
mv ./azure-resource-list/modules/fetch-resources/story.bash ./azure-resource-list/modules/fetch-resources/task.bash
mv ./vault/story.bash ./vault/task.bash
mv ./bash/modules/bash-command/story.check ./bash/modules/bash-command/task.check
mv ./bash/modules/bash-command/story.bash ./bash/modules/bash-command/task.bash
mv ./my-cool-script/story.pl ./my-cool-script/task.pl
mv ./vsts-build/modules/list/story.bash ./vsts-build/modules/list/task.bash
mv ./vsts-build/modules/run/story.bash ./vsts-build/modules/run/task.bash
mv ./ytview/story.bash ./ytview/task.bash
mv ./perl6-dir-install/story.bash ./perl6-dir-install/task.bash
mv ./geo/story.bash ./geo/task.bash
mv ./group/modules/delete/story.check ./group/modules/delete/task.check
mv ./group/modules/delete/story.bash ./group/modules/delete/task.bash
mv ./group/modules/create/story.check ./group/modules/create/task.check
mv ./group/modules/create/story.bash ./group/modules/create/task.bash
mv ./gitprep/story.bash ./gitprep/task.bash
mv ./stocks/story.bash ./stocks/task.bash
mv ./python-echo-script/story.py ./python-echo-script/task.py
mv ./catmandu/story.bash ./catmandu/task.bash
mv ./azure-storage-account/story.check ./azure-storage-account/task.check
mv ./azure-storage-account/story.ps1 ./azure-storage-account/task.ps1
mv ./ruby-echo-script/story.rb ./ruby-echo-script/task.rb
mv ./minikube-install/story.bash ./minikube-install/task.bash
mv ./azure-app-service-plan/story.ps1 ./azure-app-service-plan/task.ps1
mv ./ssl-bind-list/story.ps1 ./ssl-bind-list/task.ps1
mv ./aws-list-private-images/story.bash ./aws-list-private-images/task.bash
mv ./azure-deploy-arm/story.check ./azure-deploy-arm/task.check
mv ./azure-deploy-arm/story.ps1 ./azure-deploy-arm/task.ps1
mv ./crypt-image-smoke/modules/file-compares/story.check ./crypt-image-smoke/modules/file-compares/task.check
mv ./crypt-image-smoke/modules/file-compares/story.bash ./crypt-image-smoke/modules/file-compares/task.bash
mv ./crypt-image-smoke/modules/decrypt/story.check ./crypt-image-smoke/modules/decrypt/task.check
mv ./crypt-image-smoke/modules/decrypt/story.bash ./crypt-image-smoke/modules/decrypt/task.bash
mv ./test/story.bash ./test/task.bash
mv ./rakudo-install/story.check ./rakudo-install/task.check
mv ./rakudo-install/modules/download/story.check ./rakudo-install/modules/download/task.check
mv ./rakudo-install/modules/download/story.bash ./rakudo-install/modules/download/task.bash
mv ./rakudo-install/modules/list-available/story.bash ./rakudo-install/modules/list-available/task.bash
mv ./rakudo-install/modules/install/centos/story.check ./rakudo-install/modules/install/centos/task.check
mv ./rakudo-install/modules/install/centos/story.bash ./rakudo-install/modules/install/centos/task.bash
mv ./rakudo-install/modules/install/ubuntu/story.check ./rakudo-install/modules/install/ubuntu/task.check
mv ./rakudo-install/modules/install/ubuntu/story.bash ./rakudo-install/modules/install/ubuntu/task.bash
mv ./rakudo-install/modules/install/alpine/story.check ./rakudo-install/modules/install/alpine/task.check
mv ./rakudo-install/modules/install/alpine/story.bash ./rakudo-install/modules/install/alpine/task.bash
mv ./rakudo-install/modules/install/archlinux/story.check ./rakudo-install/modules/install/archlinux/task.check
mv ./rakudo-install/modules/install/archlinux/story.bash ./rakudo-install/modules/install/archlinux/task.bash
mv ./rakudo-install/modules/install/fedora/story.check ./rakudo-install/modules/install/fedora/task.check
mv ./rakudo-install/modules/install/fedora/story.bash ./rakudo-install/modules/install/fedora/task.bash
mv ./rakudo-install/modules/install/debian/story.check ./rakudo-install/modules/install/debian/task.check
mv ./rakudo-install/modules/install/debian/story.bash ./rakudo-install/modules/install/debian/task.bash
mv ./check-tomcat-deploy/story.check ./check-tomcat-deploy/task.check
mv ./check-tomcat-deploy/story.bash ./check-tomcat-deploy/task.bash
mv ./movies/story.bash ./movies/task.bash
mv ./aws-show-instance/story.bash ./aws-show-instance/task.bash
mv ./aws-launch-cfg-show/story.bash ./aws-launch-cfg-show/task.bash
mv ./ansible-install/story.check ./ansible-install/task.check
mv ./ansible-install/modules/debian/story.bash ./ansible-install/modules/debian/task.bash
mv ./ansible-install/story.bash ./ansible-install/task.bash
mv ./sendmail/story.check ./sendmail/task.check
mv ./sendmail/story.pl ./sendmail/task.pl
mv ./app-cpm/modules/cpm/story.check ./app-cpm/modules/cpm/task.check
mv ./app-cpm/modules/cpm/story.bash ./app-cpm/modules/cpm/task.bash
mv ./rvm/story.check ./rvm/task.check
mv ./rvm/story.bash ./rvm/task.bash
mv ./web_trawler/story.bash ./web_trawler/task.bash
mv ./vsts-schedule-build-check/story.check ./vsts-schedule-build-check/task.check
mv ./vsts-schedule-build-check/story.bash ./vsts-schedule-build-check/task.bash
mv ./taste/story.bash ./taste/task.bash
mv ./metacpan-api-packages-status/story.check ./metacpan-api-packages-status/task.check
mv ./metacpan-api-packages-status/modules/url-alert/story.check ./metacpan-api-packages-status/modules/url-alert/task.check
mv ./metacpan-api-packages-status/modules/url-alert/story.bash ./metacpan-api-packages-status/modules/url-alert/task.bash
mv ./metacpan-api-packages-status/modules/package-status/story.check ./metacpan-api-packages-status/modules/package-status/task.check
mv ./metacpan-api-packages-status/modules/package-status/story.bash ./metacpan-api-packages-status/modules/package-status/task.bash
mv ./ld-fetch-word/story.bash ./ld-fetch-word/task.bash
mv ./proc-validate/story.check ./proc-validate/task.check
mv ./proc-validate/story.bash ./proc-validate/task.bash
mv ./aws-run-instance/story.bash ./aws-run-instance/task.bash
mv ./cloudup/story.bash ./cloudup/task.bash
mv ./azure-ssl-cert-list/story.ps1 ./azure-ssl-cert-list/task.ps1
mv ./mssql-db-user/story.bash ./mssql-db-user/task.bash
mv ./stale-proc-check/story.check ./stale-proc-check/task.check
mv ./stale-proc-check/story.pm ./stale-proc-check/task.pm
mv ./perl6-prove/story.check ./perl6-prove/task.check
mv ./perl6-prove/story.bash ./perl6-prove/task.bash
mv ./qrify/story.bash ./qrify/task.bash
mv ./nano-setup/story.check ./nano-setup/task.check
mv ./nano-setup/story.bash ./nano-setup/task.bash
mv ./pwgen/story.bash ./pwgen/task.bash
mv ./gcp-bucket-anonymous-access/story.bash ./gcp-bucket-anonymous-access/task.bash
mv ./azure-authenticate/story.check ./azure-authenticate/task.check
mv ./azure-authenticate/story.ps1 ./azure-authenticate/task.ps1
mv ./cpan-package/modules/cpanm/story.check ./cpan-package/modules/cpanm/task.check
mv ./cpan-package/modules/cpanm/story.bash ./cpan-package/modules/cpanm/task.bash
mv ./docker-engine/story.check ./docker-engine/task.check
mv ./docker-engine/modules/install-ubuntu/story.check ./docker-engine/modules/install-ubuntu/task.check
mv ./docker-engine/modules/install-ubuntu/story.bash ./docker-engine/modules/install-ubuntu/task.bash
mv ./docker-engine/modules/install-debian/story.check ./docker-engine/modules/install-debian/task.check
mv ./docker-engine/modules/install-debian/story.bash ./docker-engine/modules/install-debian/task.bash
mv ./azure-ssl-bind-list/story.ps1 ./azure-ssl-bind-list/task.ps1
mv ./js-minify/story.pl ./js-minify/task.pl
mv ./chef-client-install/story.bash ./chef-client-install/task.bash
mv ./aws-cw-cpu/story.pl ./aws-cw-cpu/task.pl
mv ./mongodb/story.bash ./mongodb/task.bash
mv ./user/modules/delete/story.check ./user/modules/delete/task.check
mv ./user/modules/delete/story.bash ./user/modules/delete/task.bash
mv ./user/modules/create/story.check ./user/modules/create/task.check
mv ./user/modules/create/story.bash ./user/modules/create/task.bash
mv ./user/modules/change/story.check ./user/modules/change/task.check
mv ./user/modules/change/story.bash ./user/modules/change/task.bash
mv ./ssh-bulk-check/modules/check-host/story.check ./ssh-bulk-check/modules/check-host/task.check
mv ./ssh-bulk-check/modules/check-host/story.bash ./ssh-bulk-check/modules/check-host/task.bash
mv ./azure-service-principal-info/story.check ./azure-service-principal-info/task.check
mv ./azure-service-principal-info/story.ps1 ./azure-service-principal-info/task.ps1
mv ./azure-nic-ip-config/modules/fetch-resource/story.bash ./azure-nic-ip-config/modules/fetch-resource/task.bash
mv ./azure-nic-ip-config/modules/parse-resource/story.pl ./azure-nic-ip-config/modules/parse-resource/task.pl
mv ./bitbucket-repo-list/story.check ./bitbucket-repo-list/task.check
mv ./bitbucket-repo-list/modules/list-repos/story.check ./bitbucket-repo-list/modules/list-repos/task.check
mv ./bitbucket-repo-list/modules/list-repos/story.bash ./bitbucket-repo-list/modules/list-repos/task.bash
mv ./speedtest-cli/story.bash ./speedtest-cli/task.bash
mv ./crypt/story.bash ./crypt/task.bash
