# common settings
description: quadlet resource
type: container
rootless: false

# container related settings
containername: app_%i
hostname: app_%i
image: docker.io/nginxinc/nginx-unprivileged
network: host
label: "app=app"
templated: true
  
