# common settings
description: quadlet resource
type: container

# container related settings
rootless: false
image: docker.io/nginxinc/nginx-unprivileged
port: "8080:80"
network: host
label: "app=app"
containername: app_%i
hostname: app_%i

# network related settings
subnet: 10.10.0.0/24
gateway: 10.10.0.1
dns: 9.9.9.9
